//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialHandling.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int id { get; set; }
        public string Type { get; set; }
        public string Depth { get; set; }
        public string PartNum { get; set; }
        public string Aisle { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
